image: docker:latest

services:
  - docker:dind

stages:
  - Testing
  
before_script:
  - docker ps
    
Cypress:
  stage: Testing
  image: docker/compose
  script:
    - docker-compose up -d
    - sleep 2m # Wait for cypress to start and install all packages
    - docker ps
    - docker-compose exec -T cypress bash -c "cd src && npm ci" # make sure all packages are installed
    - docker-compose exec -T cypress bas-cypress -c --browser chrome
  after_script:
    - ls
    - docker-compose -f pipeline/docker-compose.yml -p ${CI_COMMIT_SHORT_SHA} down -v
  artifacts:
    paths:
      - artifacts/*
  when: always

