version: "3.7"
services:
  cypress:
    container_name: cypress
    image: gitlab.buyandsell.gc.ca:4567/qa/cypress
    restart: "no"
    volumes:
      - .:/src
      - ./pipeline/artifacts:/home/docker/artifacts
    ports:
      - 6901:6901
  chromium:  
    container_name: chromium
    image: overclockedllama/docker-chromium
    build: .
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/chromium:/config:rw"
