version: '3.7'
services:
  cypress-chrome:
      container_name: cypress-chrome
      image: gitlab.buyandsell.gc.ca:4567/qa/cypress:latest
      restart: "no"
      volumes:
      - ${CI_PROJECT_DIR}/artifacts/videos:/src/cypress/videos
      - ${CI_PROJECT_DIR}/artifacts/screenshots:/src/cypress/screenshots
      - ${CI_PROJECT_DIR}/cypress:/src/cypress
      - ${CI_PROJECT_DIR}/cypress.json:/src/cypress.json
  cypress-firefox:
      container_name: cypress-firefox
      image: gitlab.buyandsell.gc.ca:4567/qa/cypress:latest
      restart: "no"
      volumes:
      - ${CI_PROJECT_DIR}/artifacts/videos:/src/cypress/videos
      - ${CI_PROJECT_DIR}/artifacts/screenshots:/src/cypress/screenshots
      - ${CI_PROJECT_DIR}/cypress:/src/cypress
      - ${CI_PROJECT_DIR}/cypress.json:/src/cypress.json
  cypress-edge:
      container_name: cypress-edge
      image: gitlab.buyandsell.gc.ca:4567/qa/cypress:latest
      restart: "no"
      volumes:
      - ${CI_PROJECT_DIR}/artifacts/videos:/src/cypress/videos
      - ${CI_PROJECT_DIR}/artifacts/screenshots:/src/cypress/screenshots
      - ${CI_PROJECT_DIR}/cypress:/src/cypress
      - ${CI_PROJECT_DIR}/cypress.json:/src/cypress.json
